# Generated by Django 2.2.4 on 2021-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
