# Generated by Django 2.2.4 on 2021-06-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210604_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'instructor')], primary_key=True, serialize=False),
        ),
    ]
