# Generated by Django 2.2.4 on 2021-06-03 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attend',
            field=models.CharField(default='optional', max_length=255),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 16, 49, 16, 419260)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 3, 16, 49, 16, 427255)),
        ),
    ]
