# Generated by Django 2.2.4 on 2021-06-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210603_1649'),
        ('student', '0002_auto_20210603_1346'),
    ]

    operations = [
    ]
