# Generated by Django 2.2.4 on 2021-06-05 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210604_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 5, 10, 14, 14, 282599)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 5, 10, 14, 14, 298223)),
        ),
    ]
