# Generated by Django 2.2.4 on 2021-06-05 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20210605_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 5, 11, 1, 55, 237201)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 5, 11, 1, 55, 268447)),
        ),
    ]
